### ISSUE TITLE
jsDelivr auto-updates

### ISSUE THREAD

**Issue by jimaek** [avielfedida/ISO8601-Localizer#1]
Is there any chance for you to switch to using lowercase names for your files?
Thats what you have here https://github.com/jsdelivr/jsdelivr/blob/master/files/iso8601-localizer/update.json and already here https://github.com/jsdelivr/jsdelivr/tree/master/files/iso8601-localizer/1.0.4

Because of this auto-updates are not working

**Comment by avielfedida** [comment]
Sure I will, thank you.

**Comment by jimaek** [comment]
Great thank you
